development: &default
  adapter: postgresql
  database: myblog_development
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: myblog_test

production:
  <<: *default
  database: myblog_production
